### PR TITLE
Fix Raspberry PI Model in MQTT Auto Discovery.

### PR DESCRIPTION
**Pull request by maorcc**
In MQTT auto-discovery, the "Model" field was always empty,
Fixed the code to support case-insensitive strings in the command output.

### CODE REVIEW

**Comment by maorcc** [comment]
Alternatively, we can use the command below to show a more readable Raspberry PI model name:
```
$ cat /sys/firmware/devicetree/base/model
Raspberry Pi Zero W Rev 1.1
```

**Comment by hjelev** [comment]
wifi branch is merged to master

**Comment by hjelev** [comment]
Your suggestion is not working well on multi core models, check the output on my rpi4

~ » cat /proc/cpuinfo | grep -i model | sed 's/[Mm]odel.*: //g'                                                                                                                                        pi@rpi4-ssd
ARMv7 Processor rev 3 (v7l)
ARMv7 Processor rev 3 (v7l)
ARMv7 Processor rev 3 (v7l)
ARMv7 Processor rev 3 (v7l)
Raspberry Pi 4 Model B Rev 1.4

The model is filtered on purpus with capital M , as only this line contains the full name we need.

~ » cat /proc/cpuinfo | grep -i model                                                                                                                                                                  pi@rpi4-ssd
model name	: ARMv7 Processor rev 3 (v7l)
model name	: ARMv7 Processor rev 3 (v7l)
model name	: ARMv7 Processor rev 3 (v7l)
model name	: ARMv7 Processor rev 3 (v7l)
Model		: Raspberry Pi 4 Model B Rev 1.4

**Comment by maorcc** [comment]
So I suggest using the `cat /proc/cpuinfo` command for PI4, and if it provides nothing, run the `cat /sys/firmware/devicetree/base/model` command that works well on PI Zero.

This is the output on PI Zero:

```
$ cat /sys/firmware/devicetree/base/model
Raspberry Pi Zero W Rev 1.1
```

Hopefully, this strategy will also work well on other PIs.

**Comment by hjelev** [comment]
cat /sys/firmware/devicetree/base/model - this one works but what is the problem with the current one isn't it working on pi zero?

**Comment by maorcc** [comment]
Here is the full output on PI Zero. As you can see, there is no "Model" row:
```
$ cat /proc/cpuinfo
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 997.08
Features        : half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2835
Revision        : 9000c1
Serial          : 0000000022222222
```

**Comment by hjelev** [comment]
This should be fixed in master now

**Pull request closed without merging**
